# Generated by Django 6.0.4 on 2026-04-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_chatsession_chatmessage_uploadedcase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="uploadedcase",
            name="file",
            field=models.FileField(max_length=500, upload_to="cases/"),
        ),
        migrations.AlterField(
            model_name="uploadedcase",
            name="filename",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
